name: test1
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install nodejs18
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm ci
      - name : run npm lint
        run: npm run lint
      - name: run test
        run: npm test
      - name: run build
        run: npm run build
      - name: deploy application
        run: echo "deploy application"